import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/registry";
import Providers from "./providers/Providers";
import { Roboto } from "next/font/google";
import Navigation from "./components/Navigation/Navigation";
import Footer from "./components/Footer/Footer";

const roboto = Roboto({
  style: ["normal"],
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" className={roboto.className}>
        <body>
          <Navigation />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
